[package]
name = "blink-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand_core = "0.6.4"

[dependencies.k256]
version = "0.13.1"
default-features = false
features = ["ecdsa"]

[lib]
name       = "app"
test       = false
bench      = false
crate-type = ["bin"]
